pipeline:
  identifier: Build_harness_CI_python_1735612606152
  name: Build harness_CI_python
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: bc_github
        repoName: harness_CI_python
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: bjc77731
                    repo: bjc77731/harness-python-ci
                    tags:
                      - latest
                      - 1.0.0
                    caching: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: minikube
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
        type: CI
